### ISSUE TITLE
Kubernetes repo access issue -20.12

### ISSUE THREAD

**Issue by ravicorning** [open-ness/converged-edge-experience-kits#106]
I'm on 20.12 version, when I tried reinstalling the controller, I'm having issue getting the K8S packages, also going to the URL dont see any binaries there..
##

TASK [machine_setup/os_setup : install base OS rpm packages] *****************************************************************************************************************************************************
task path: /home/ravi/openness-experience-kits/roles/machine_setup/os_setup/tasks/install_base_os_packages.yml:27
Error occurred. Will retry after 5 seconds. You can find details below:
Failure talking to yum: failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes

Retrying task - attempt 2 of 10
Error occurred. Will retry after 5 seconds. You can find details below:
Failure talking to yum: failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes

**Comment by amr-mokhtar** [comment]
Seems to be the same issue #107 that is observable on 21.03 release

**Comment by amr-mokhtar** [comment]
This has been fixed on OpenNESS 21.03 tag `openness-21.03.01`.
@ravicorning Are you okay to close?

**Comment by ravicorning** [comment]
Sure Amr, thanks.
