### ISSUE TITLE
Container image "certrequester:1.0" / "certsigner:1.0" is not present

### ISSUE THREAD

**Issue by Jorge-Sasiain** [open-ness/converged-edge-experience-kits#109]
Hello all,

Found this issue during the installation of an edge node in OpenNESS-21.03.

Deployment fails with the following error (I can provide the whole log file if needed):

```
TASK [applications/openness/node : wait for Kafka CA and User secrets] ***********************************************************************************************************************************************************
task path: /home/centos/converged-edge-experience-kits/roles/applications/openness/node/tasks/prebuild/kafka_certs.yml:24
Tuesday 06 April 2021  10:42:40 +0200 (0:00:00.527)       0:17:01.534 *********
FAILED - RETRYING: wait for Kafka CA and User secrets (60 retries left).
(...)
FAILED - RETRYING: wait for Kafka CA and User secrets (49 retries left).
fatal: [node01 -> 10.98.1.47]: FAILED! => {
    "attempts": 13,
    "changed": false,
    "cmd": "restartCounts=`kubectl get pods -n kafka -o json | jq -r '.items[] | [.status.containerStatuses[].restartCount] | @sh'`\nfor restartCount in $restartCounts; do\n  if [ $((restartCount + 0)) -gt 10 ]; then\n    exit -1\n  fi\ndone\nkubectl get secret cluster-cluster-ca-cert -n kafka && kubectl get secret eaa-kafka -n kafka\n",
    "delta": "0:00:00.139783",
    "end": "2021-04-06 10:54:53.666661",
    "rc": 255,
    "start": "2021-04-06 10:54:53.526878"
}
```
Upon inspecting the kubectl status, I noticed the pods in the openness namespaces are mostly in an error state:
```
openness        certsigner-6cb79468b5-wf6vt                                  0/1     ErrImageNeverPull        0          4d20h
openness        eaa-69c7bb7b5d-2nlcm                                         0/1     Init:0/2                 0          4d20h
openness        edgedns-kxqr9                                                0/1     Init:ErrImageNeverPull   0          23m
openness        interfaceservice-2m6m2                                       0/1     Init:ErrImageNeverPull   0          23m
openness        nfd-release-node-feature-discovery-master-5cf6848cfd-mgbns   1/1     Running                  0          4d20h
openness        nfd-release-node-feature-discovery-worker-r6mr2              0/1     CrashLoopBackOff         10         23m
```
Checking the pods individually reveals errors indicating that the certsigner or certrequester images can't be pulled. For example, the ``describe pod`` output of interfaceservice:

`Warning  ErrImageNeverPull  3m24s (x72 over 18m)  kubelet            Container image "certrequester:1.0" is not present with pull policy of Never`

Indeed, checking ``docker image list`` in the edgenode shows that the images are not there, and I don't see them anywhere in Harbor either.

After looking around a bit, I attempted building these images manually from the open-ness/edgeservices repository. After doing this, the messages change to:

`  Normal   Pulled     97s (x5 over 3m4s)    kubelet            Container image "certrequester:1.0" already present on machine`

But the pods remain in error state. The docker logs of the interfaceservice, for example, show this:

```
<7>Apr  6 09:53:23 certrequester[1]: Config: certrequester.Config{CSR:certrequester.CSRConfig{Name:"interfaceservice-openness-edgenode", Subject:pkix.Name{Country:[]string(nil), Organization:[]string(nil), OrganizationalUnit:[]string(nil), Locality:[]string(nil), Province:[]string(nil), StreetAddress:[]string(nil), PostalCode:[]string(nil), SerialNumber:"", CommonName:"interfaceservice.openness", Names:[]pkix.AttributeTypeAndValue(nil), ExtraNames:[]pkix.AttributeTypeAndValue(nil)}, DNSSANs:[]string{"interfaceservice.openness"}, IPSANs:[]net.IP{}, KeyUsages:[]v1.KeyUsage{"server auth", "key encipherment", "digital signature"}}, Signer:"openness.org/certsigner", WaitTimeout:util.Duration{Duration:300000000000}}
<6>Apr  6 09:53:23 certrequester[1]: [certrequester] X509 key pair not valid: open ./certs/cert.pem: no such file or directory
<6>Apr  6 09:53:23 certrequester[1]: [certrequester] Continuing to generate key pair...
<3>Apr  6 09:53:53 certrequester[1]: Failed to generate certificate: Failed to remove old CSR: Delete "https://10.112.0.1:443/apis/certificates.k8s.io/v1/certificatesigningrequests/interfaceservice-openness-edgenode": dial tcp 10.112.0.1:443: i/o timeout
```

So it seems that the creation of the certsigner and certrequester images needs to be done during the deployment with the experience kits. This could be an issue with my setup but I'm not sure how to progress from here. Any input would be appreciated; let me know if other information from the setup or deployment would be relevant here.

Thanks in advance.

**Comment by swapneel100** [comment]
Hello, 

I would recommend you to clean up the setup, and try deploying the setup once again using OpenNESS-21.03.02. If you continue to face the same issue, kindly share the log file. Thank you.

**Comment by Jorge-Sasiain** [comment]
Forgot to add here, but after reinstalling for a third time (sometime last month), everything worked perfectly. I couldn't really figure out what it was, so I'm sorry to not be able to provide more information about it. I would say I always used the same setup but I could've missed something the first two times, or could've been a temporary issue. But I will close this issue now as it's solved already. Thanks.
