### ISSUE TITLE
downlaoding of packages on edgenode failed 

### ISSUE THREAD

**Issue by ashishsaxenahsc** [open-ness/converged-edge-experience-kits#13]
While depoying edgenode in On-premise mode, I am getting the following error:

task path: /root/openness-experience-kits/roles/machine_setup/configure_tuned/tasks/configure_tuned.yml:6
fatal: [edgenode]: FAILED! => {
    "changed": false
}

MSG:

Failure downloading http://linuxsoft.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-5.el7_7.1.noarch.rpm, HTTP Error 404: Not Found

The url "http://linuxsoft.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-5.el7_7.1.noarch.rpm" is found to be not reachable.

Can you please provde some way of fixing this issue , or provide alternatine url for the same.

**Comment by amr-mokhtar** [comment]
Which OpenNESS release are you based on?

**Comment by ashishsaxenahsc** [comment]
It’s latest Release 20.03, and I am using branch oek-pull-2003-tag.

**Comment by amr-mokhtar** [comment]
Thanks @ashishsaxenahsc for the heads up. I have created a known-issue for it #14 with a proposed fix.

**Comment by ishanVshah** [comment]
@ashishsaxenahsc  you can change the URL inside the file "/root/openness-experience-kits/roles/machine_setup/configure_tuned/defaults" as below and try to execute again.

 http://linuxsoft.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-5.el7_7.2.noarch.rpm
