### ISSUE TITLE
broken tuned_packages links

### ISSUE THREAD

**Issue by amr-mokhtar** [open-ness/converged-edge-experience-kits#14]
It was observed that tuned package download links are broken as reported in #13 -- thanks to @ashishsaxenahsc.

The tuned_packages links can be updated to the following files:
1. openness-experience-kits/group_vars/edgenode_group.yml
2. openness-experience-kits/host_vars/_example_variables.yml
3. openness-experience-kits/roles/machine_setup/configure_tuned/defaults/main.yml

Update:
```
- - http://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/tuned-2.11.0-5.el7_7.1.noarch.rpm
- - http://linuxsoft.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-
+ - http://linuxsoft.cern.ch/scientific/7x/x86_64/os/Packages/tuned-2.11.0-8.el7.noarch.rpm
+ - http://linuxsoft.cern.ch/scientific/7x/x86_64/os/Packages/tuned-profiles-realtime-2.11.0-8.el7.noarch.rpm
```

**Comment by calinghe** [comment]
@amr-mokhtar - so is this solution planned to be patched into the repo?

**Comment by amr-mokhtar** [comment]
@calinghe Yes, should have been fixed in the 20.06 release.

**Comment by jamescch** [comment]
These links broke again. 
And this time has changed to `tuned-2.11.0-9.el7.noarch.rpm` and `tuned-profiles-realtime-2.11.0-9.el7.noarch.rpm`

**Comment by amr-mokhtar** [comment]
> These links broke again.
> And this time has changed to `tuned-2.11.0-9.el7.noarch.rpm` and `tuned-profiles-realtime-2.11.0-9.el7.noarch.rpm`

Can you please raise a new issue for this one, so that it is addressed by the engineering team?
If you were able to find a work-around, please mention that too.
Thanks @jamescch
