### ISSUE TITLE
Not able to login Controller GUI on-premises openness edge controller

### ISSUE THREAD

**Issue by ishanVshah** [open-ness/converged-edge-experience-kits#16]
Post installation of on-premises edge controller, I am able to access the GUI but i am not able to login.

Error on browser "Login Failed Try again Later".

I am using "admin" as a default username and password is "pass" which is mentioned in file group_vars/all.yaml file.

please help me on this.

**Comment by amr-mokhtar** [comment]
Can you check the controller logs? Did any of the dockers exit?

**Comment by ishanVshah** [comment]
Are you taking about docker container logs ?

**Comment by ishanVshah** [comment]
[root@XXXX edgecontroller]# docker logs --follow edgecontroller_ui_1
Server listening on port 80.

**Comment by amr-mokhtar** [comment]
All of the controller containers.

**Comment by ishanVshah** [comment]
@amr-mokhtar  all controller having same logs 

"Server listening on port 80."

**Comment by ishanVshah** [comment]
@amr-mokhtar  screenshot of the controller GUI
![Capture](https://user-images.githubusercontent.com/59759055/82567564-2b7bef00-9b9b-11ea-9523-e7f36b4a17c5.JPG)

**Comment by amr-mokhtar** [comment]
I haven’t seen this before but there are two potential causes that I can think of.

1. Check the .env file in the install location of edgecontroller (/opt/edgecontroller), it includes the password when edgecontroller is installed. It could have been set to something else during the install but the one there is the one that is expected by the controller.
2. Check that the REACT_APP_CONTROLLER_API value in .env in the install folder for edgecontroller (/opt/edgecontroller) is set to the correct IP address for the edgecontroller. When logging into the UI, it makes a call to the authentication API (https://www.openness.org/api-documentation/?api=controller#/Login/post_auth) of the Controller and if the wrong IP address was provided in the .env, then the UI will fail to log in due to an incorrect connection.

**Comment by ishanVshah** [comment]
@amr-mokhtar I have reverified both points and all looks good but still no luck :-(

please check logs of edgecontroller_cce_1

#docker logs --follow edgecontroller_cce_1
<135>May 21 14:51:53 cce[1]: [proxy] Connection from xxx.xx.xx.12:58172, awaiting 1st packet
<135>May 21 14:51:53 cce[1]: [proxy] First packet received, 3/3 bytes: "ELA"
<135>May 21 14:51:53 cce[1]: [proxy] we have ELA proxy callback from xxx.xx.xx.12

**Comment by ishanVshah** [comment]
@amr-mokhtar Requesting you to please solve my query as i have this infrastructure for limited period of time.

I really appreciate if you please help me here.

**Comment by amr-mokhtar** [comment]
I can't really say what is wrong.. It is quite straight forward to install as long as you're using the Ansible playbooks provided with OEK. I advised that you verify that your system meets pre-requisites defined in the doc and avoid any manual changes.
If still not able to figure out what is wrong. Try to clean up the systems and re-install, there probably something went wrong during installation.

**Comment by amr-mokhtar** [comment]
I will forward this issue internally to see if there is anything else can be done.

**Comment by i-karina** [comment]
Could you provide ansible logs from installation? Also we've observed similar issue when IP address of controller in inventory.ini was set to 127.0.0.1 (it is not allowed).

**Comment by ishanVshah** [comment]
Hi @amr-mokhtar @i-karina  I installed On-premises on servers (1 edge controller and 1 edge node).

I didn't have an SSH access of direct servers. first I have to take SSH of Jump server and then i am able to SSH of servers. take GUI access of controllers on my laptop using SSH port forwarding and may be there is an issue on my laptop.

last i installed no machine on Jump server and take a GUI access of edge controller from Jumpp server and it is working fine.

**Comment by ishanVshah** [comment]
@amr-mokhtar  requesting you to please close this ticket and i appreciate to you and team. thanks a lot !!
