### ISSUE TITLE
wait for running ovs-ovn and ovn-central pods

### ISSUE THREAD

**Issue by splendid18** [open-ness/converged-edge-experience-kits#18]
We are getting "wait for running ovs-ovn and ovn-central pods" while installing OpenNESS 20.03 in network edge deployment mode.

We ran the script deploy_ne.sh multiple times, but every time it's failing at the same point. What could be the possible reasons?
![image](https://user-images.githubusercontent.com/9364412/83677892-7ca7cc00-a5fa-11ea-92b8-67c19a187412.png)
[2020-06-03_23-55-34_ansible.log](https://github.com/open-ness/openness-experience-kits/files/4725633/2020-06-03_23-55-34_ansible.log)

**Comment by splendid18** [comment]
The pod status was in a pending state. on further investigation, it was found that the hugepages were insufficient at 2Mi in roles/kubernetes/cni/kubeovn/common/defaults/main.yml. On changing it to 1Gi, it worked.

**Comment by pedrocruz** [comment]
Hello,
I am running ./deploy_ne.sh -f minimal single.
I tried the same solution by ashurvcs, but it didn't work.

I am trying to deploy OpenNESS on a 11GB RAM virtual machine (the centOS version indicated in the docs).

After 30 retries, this is the message I get:

`fatal: [controller]: FAILED! => {`
`    "attempts": 30, `
`    "changed": false, `
`    "cmd": "set -o pipefail && kubectl get pods -n kube-system -o custom-columns=NAME:.metadata.name,STATUS:.status.phase --no-headers --field-selector spec.nodeName=test | grep -E \"ovs-ovn|ovn-central\"\n", `
`    "delta": "0:00:00.136883", `
`    "end": "2020-12-03 09:37:27.438807", `
`    "rc": 0, `
`    "start": "2020-12-03 09:37:27.301924"`
`}`
`STDOUT:`
`ovs-ovn-vnq2k                          Running`
