### ISSUE TITLE
Not able to login into OpenNess Controller GUI

### ISSUE THREAD

**Issue by illuri-537** [open-ness/converged-edge-experience-kits#21]
![controller GUI](https://user-images.githubusercontent.com/36484257/84999121-a60f3e80-b148-11ea-9d21-951e607a5e99.PNG)

Unable to login into OpenNess Controller UI

**Comment by amr-mokhtar** [comment]
Can you check this closed issue #16 - it seems similar.

**Comment by illuri-537** [comment]
@amr-mokhtar  I went through the #16 but its not resolved

**Comment by tomaszwesolowski** [comment]
hi @illuri-537, 
Is this problem still happening or is it resolved?
