### ISSUE TITLE
Issue while  running deploy_ne.sh

### ISSUE THREAD

**Issue by JeevanCK7** [open-ness/converged-edge-experience-kits#22]
Hi @amr-mokhtar 

1. I had already ran deploy_ne.sh script and installed everything. Later tried to cleanup and re-deploy network edge.
2. Im facing error while running "./deploy_ne.sh controller " script as mentioned below

fatal: [controller]: FAILED! => {
    "changed": false
}

MSG:

Could not find the requested service kubelet: host
****

3.Kindly help me to resolve this.

**Comment by amr-mokhtar** [comment]
This sounds like that clean script did not run to completion

**Comment by gyan1230** [comment]
I am also facing same issue.

**Comment by amr-mokhtar** [comment]
This seems to be affected by this bug in Kubernetes
https://github.com/kubernetes/kubernetes/issues/92242

**Comment by gyan1230** [comment]
Is there  any workaround until the repo is fixed? 
Is there anyway to  use the --setopt=obsoletes=0 option when running yum install in the ansible playbook?
how to add this flag in  ansible playbook?

**Comment by amr-mokhtar** [comment]
This is the Ansible task that installs K8s
https://github.com/open-ness/openness-experience-kits/blob/051b7537837b634135724d829318670f000e207b/roles/kubernetes/common/tasks/main.yml#L16

**Comment by JeevanCK7** [comment]
@amr-mokhtar can you pls tell how to overcome this issue exactly?

**Comment by JeevanCK7** [comment]
@amr-mokhtar I have come across this too
fatal: [controller]: FAILED! => {
    "changed": true, 
    "cmd": [
        "grep", 
        "0", 
        "/proc/sys/net/bridge/bridge-nf-call-iptables", 
        "/proc/sys/net/bridge/bridge-nf-call-ip6tables"
    ], 
    "delta": "0:00:01.004063", 
    "end": "2020-06-22 12:28:28.555635", 
    "rc": 1, 
    "start": "2020-06-22 12:28:27.551572"
}

MSG:

non-zero return code

But this is ignored.

**Comment by amr-mokhtar** [comment]
As an interim work-around, you can try to install Kubernetes 1.18.4.
To do this, update the [file](https://github.com/open-ness/openness-experience-kits/blob/master/roles/kubernetes/common/defaults/main.yml) with the below
```
_kubernetes_version: "1.18.4"
```

Disclaimer: This may break other things as that 20.03 was not tested with that version.
