### ISSUE TITLE
Error while installing telemetry/tas 

### ISSUE THREAD

**Issue by vaghesh** [open-ness/converged-edge-experience-kits#27]
When installing in single node cluster, it throws the error on task to build TAS

TASK [telemetry/tas : build TAS] *************************************************************************************************
task path: /root/openness-experience-kits/roles/telemetry/tas/tasks/main.yml:154
fatal: [controller]: FAILED! => {
    "changed": true, 
    "cmd": "source /etc/profile && make build", 
    "delta": "0:00:02.121611", 
    "end": "2020-07-02 00:04:40.110584", 
    "rc": 2, 
    "start": "2020-07-02 00:04:37.988973"
}

STDOUT:

CGO_ENABLED=0 GO111MODULE=on go build -ldflags="-s -w" -o ./bin/controller ./cmd/tas-policy-controller

STDERR:

go: finding modernc.org/golex v1.0.0
go: finding modernc.org/mathutil v1.0.0
go: finding modernc.org/xc v1.0.0
go: finding modernc.org/cc v1.0.0
go: finding modernc.org/strutil v1.0.0
go: modernc.org/golex@v1.0.0: git fetch -f https://gitlab.com/cznic/golex refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/9aae2d4c6ee72eb1c6b65f7a51a0482327c927783dea53d4058803094c9d8039: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/mathutil@v1.0.0: git fetch -f https://gitlab.com/cznic/mathutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/fb72eb2422fda47ac75ca695d44b06b82f3df3c5308e271486fca5e320879130: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/xc@v1.0.0: git fetch -f https://gitlab.com/cznic/xc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/29fc2f846f24ce3630fdd4abfc664927c4ad22f98a3589050facafa0991faada: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/strutil@v1.0.0: git fetch -f https://gitlab.com/cznic/strutil refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/f48599000415ab70c2f95dc7528c585820ed37ee15d27040a550487e83a41748: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: modernc.org/cc@v1.0.0: git fetch -f https://gitlab.com/cznic/cc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/3dac616a9d80602010c4792ef9c0e9d9812a1be8e70453e437e9792978075db6: exit status 128:
	error: RPC failed; result=22, HTTP code = 404
	fatal: The remote end hung up unexpectedly
go: error loading module requirements
make: *** [build] Error 1

MSG:

non-zero return code

**Comment by archie95** [comment]
@amr-mokhtar I am also facing the failure at this step while deploying the network edge for the new OpenNESS 20.06 version. Please help.

**Comment by amr-mokhtar** [comment]
This is happening due to installing on a previous installation. To overcome this issue, you can manually install the correct git version:
```shell
yum remove git* -y
yum install -y --enablerepo=ius-archive git2u-all
```

**Comment by archie95** [comment]
Thanks @amr-mokhtar. It is working now. Able to install now. You can close this.
