### ISSUE TITLE
Error while deploying Edge Node

### ISSUE THREAD

**Issue by pavanats** [open-ness/converged-edge-experience-kits#34]
Hi,
I have been able to deploy Edge Controller on a physical machine. While deploying the edge node using the Ansible script, I am coming across the following error. Both my edge controller and node are on separate physical servers. The error below was also seen on a VM setup. I have also manually tried the command that failed but it gives the same error. 

### TASK [kubernetes/cni/kubeovn/worker : try to get ovs-ovn                                                                                                   execution logs] ***************************************                                                                                                  ******************************************
task path: /root/openness-experience-kits/roles/kubernet                                                                                                  es/cni/kubeovn/worker/tasks/main.yml:75
fatal: [node01 -> x.x.x.x]: FAILED! => {
    "changed": false,
    "cmd": "set -o pipefail && kubectl logs -n kube-system $(kubectl get pods -n kube-system -o custom-columns=NAME:.metadata.name --field-selector spec.nodeName=node01                                                                                                   | grep ovs-ovn)\n",
    "delta": "0:00:00.266311",
    "end": "2020-07-15 16:53:57.933688",
    "rc": 1,
    "start": "2020-07-15 16:53:57.667377"
}

STDERR:

Error from server: Get https://x.x.x.x:10250/containerLogs/kube-system/ovs-ovn-tgfq6/openvswitch: dial tcp x.x.x.x:10250: connect: connection refused

MSG:

non-zero return code
...ignoring

TASK [kubernetes/cni/kubeovn/worker : end the playbook]                                                                                                   ********************************************************                                                                                                  ******************************************
task path: /root/openness-experience-kits/roles/kubernet                                                                                                  es/cni/kubeovn/worker/tasks/main.yml:84
fatal: [node01]: FAILED! => {
    "changed": false
}

MSG:

end the playbook: either ovs-ovn pod did not start or the socket was not created

**Comment by tomaszwesolowski** [comment]
Hi, 
Can you provide your configuration files? Also if you could provide output from `kubectl get pods -A -o wide` command it would be helpful.

**Comment by pavanats** [comment]
My controller and node have been successfully deployed, so dont have the CLI output for the failure condition. But these errors occurred for quite a while before getting a successful deployment.
Pavan
________________________________

**Comment by tomaszwesolowski** [comment]
The same problem a few times? Maybe there was some network issue. Anyway we will monitor situation. Thank you for your feedback and let us know if the problem returns.
