### ISSUE TITLE
Some pods in completed state after deploying the controller and edge node

### ISSUE THREAD

**Issue by pavanats** [open-ness/converged-edge-experience-kits#35]
Hi,
I see there are some pods in completed state after deploying the controller and the edge node. Is this fine? 

[root@controller ~]# kubectl get pods -o wide -A | grep Completed
kube-system   descheduler-cronjob-1594902000-v5w9x                        0/1     Completed   0          4m52s   10.16.0.26        node01       <none>           <none>
kube-system   descheduler-cronjob-1594902120-tv5cz                        0/1     Completed   0          2m52s   10.16.0.32        node01       <none>           <none>
kube-system   descheduler-cronjob-1594902240-wgrqt                        0/1     Completed   0          51s     10.16.0.33        node01       <none>           <none>
telemetry     telemetry-collector-certs-hrf96                             0/1     Completed   0          150m    10.16.0.12        node01       <none>           <none>

For the telemetry collector pod, I ran the pod describe command and the output shows a taint:

[root@controller ~]# kubectl describe pods telemetry-collector-certs-hrf96 -n telemetry
Name:         telemetry-collector-certs-hrf96
Namespace:    telemetry
Priority:     0
Node:         node01/134.119.205.185
Start Time:   Thu, 16 Jul 2020 14:03:30 +0200
Labels:       controller-uid=287b90cf-5d41-42a7-9b65-b7dab0069d71
              job-name=telemetry-collector-certs
              name=telemetry-collector-certs
Annotations:  ovn.kubernetes.io/allocated: true
              ovn.kubernetes.io/cidr: 10.16.0.0/16
              ovn.kubernetes.io/gateway: 10.16.0.1
              ovn.kubernetes.io/ip_address: 10.16.0.12
              ovn.kubernetes.io/logical_switch: ovn-default
              ovn.kubernetes.io/mac_address: de:fd:f8:10:00:0d
Status:       Succeeded
IP:           10.16.0.12
IPs:
  IP:           10.16.0.12
Controlled By:  Job/telemetry-collector-certs
Containers:
  openssl:
    Container ID:  docker://517f8b221c82b5d1969c3e4e5648fdefde2c8bda70359314040bdfede98a3aea
    Image:         emberstack/openssl:latest
    Image ID:      docker-pullable://emberstack/openssl@sha256:1fad327428e28ac1138444fca06000c2bf04b5efb56e85440f5cbfb25e40a122
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      rm -Rf /root/certs/otel_collector && mkdir /root/certs/otel_collector && /root/certgen/entrypoint_tls.sh otel_collector /root/certs/otel_collector /root/CA && chmod 644 /root/certs/otel_collector/cert.pem /root/certs/otel_collector/key.pem && rm -Rf /root/certs/otel-collector.telemetry.svc && rm -rf /root/ca && mkdir /root/certs/otel-collector.telemetry.svc && /root/certgen/entrypoint_tls.sh otel-collector.telemetry.svc /root/certs/otel-collector.telemetry.svc /root/CA && chmod 644 /root/certs/otel-collector.telemetry.svc/cert.pem /root/certs/otel-collector.telemetry.svc/key.pem
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 16 Jul 2020 14:04:25 +0200
      Finished:     Thu, 16 Jul 2020 14:04:26 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:        100m
      memory:     128Mi
    Environment:  <none>
    Mounts:
      /root/CA from ca (rw)
      /root/certgen from certgen (rw)
      /root/certs from cert-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5vv4m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  cert-vol:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/openness/certs/telemetry
    HostPathType:  DirectoryOrCreate
  ca:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  root-ca
    Optional:    false
  certgen:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  certgen
    Optional:    false
  default-token-5vv4m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5vv4m
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/2 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate, 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
  Normal   Scheduled         <unknown>  default-scheduler  Successfully assigned telemetry/telemetry-collector-certs-hrf96 to node01
  Normal   Pulling           29m        kubelet, node01    Pulling image "emberstack/openssl:latest"
  Normal   Pulled            28m        kubelet, node01    Successfully pulled image "emberstack/openssl:latest"
  Normal   Created           28m        kubelet, node01    Created container openssl
  Normal   Started           28m        kubelet, node01    Started container openssl

**Comment by tomaszwesolowski** [comment]
Hi,
Yes, some pods are expected to be in Completed state after successful finished deployment.
