### ISSUE TITLE
Single-node Network Edge cluster on VM - installation error

### ISSUE THREAD

**Issue by anishraw** [open-ness/converged-edge-experience-kits#41]
hi , 
I am using the latest openNESS20.06.
trying to have a Single-node Network Edge cluster on a VM machine(KVM based).
Every time my installation getting stuck at  

```
TASK [kubernetes/cni/kubeovn/master : create temp crd_local.yml] *******************************************************************************************************************************
task path: /home/kit/openness-experience-kits/roles/kubernetes/cni/kubeovn/master/tasks/main.yml:132
fatal: [nodectrl]: FAILED! => {
    "changed": false,
    "checksum": "b52d0515bb11a9a5d1cbe2b2ca2e2ade0287c80b"
}

MSG:

Destination directory /opt/edgenode/network-edge/kube-ovn does not exist

PLAY RECAP *************************************************************************************************************************************************************************************
nodectrl                   : ok=239  changed=67   unreachable=0    failed=1    skipped=107  rescued=0    ignored=4
```

![image](https://user-images.githubusercontent.com/59694526/88658146-473bce00-d0d3-11ea-9f8e-781aa454a97f.png)

for the pod in pending status 

![image](https://user-images.githubusercontent.com/59694526/88658214-5e7abb80-d0d3-11ea-85c5-5422350ba8b6.png)

OVS DPDK related values are
![image](https://user-images.githubusercontent.com/59694526/88658319-8538f200-d0d3-11ea-891f-0fc298644353.png)

ADDED info 
logs from /car/log/openswitch/ovn-controller.log

![image](https://user-images.githubusercontent.com/59694526/88660725-9683fd80-d0d7-11ea-9ef2-0014f5fa6c46.png)

**any inputs to remove this installation error?**
thanks

**Comment by tomaszwesolowski** [comment]
hi,
Can you provide contents of inventory.ini file?

**Comment by i-kwilk** [comment]
There is no response from the user, therefore, we are closing the issue.
