### ISSUE TITLE
Issue while deploying openness worker-node

### ISSUE THREAD

**Issue by Jaladi-Devika** [open-ness/converged-edge-experience-kits#43]
Hi,

Have ran ./deploy_ne.sh nodes. But failed with below error.
Worker-node is pingable and able do ssh as well.

<img width="826" alt="connection_refused" src="https://user-images.githubusercontent.com/66933956/90477556-3c5fe080-e149-11ea-9ee0-df5123157329.PNG">
<img width="817" alt="connection_refused_0" src="https://user-images.githubusercontent.com/66933956/90477560-3e29a400-e149-11ea-84fe-fb591d18d171.PNG">

Can you please help me how to resolve this issue?

Thanks & Regards,
Devika

**Comment by i-kwilk** [comment]
Hi Davika,
Can you send the configuration that you are having by sending all git changes that you have made?
Thanks,
Krzysztof

**Comment by Jaladi-Devika** [comment]
HI,

below are the configuration have followed
1. set the hostnames
On controller:  $ hostnamectl set-hostname controller
On worker_node: $ hostnamectl set-hostname node01

2. hostname devined in /etc/hosts
On master node:
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 controller
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 controller
On worker node:
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 node01
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 node01

3. Did below thing in inventory.ini
   [all]
   controller ansible_ssh_user=root ansible_host=192.168.10.91 
   node01 ansible_ssh_user=root ansible_host=192.168.10.92

    [controller_group]
    controller

    [edgenode_group]
    node01

    [edgenode_vca_group]

    [ptp_master]
    controller

    [ptp_slave_group]
    node01 

4. ssh-keygen
5. ssh-copy-id root@192.168.10.92

6. Did below changes in group_vars/all/10-default.yml
   Network Time Protocol (NTP)
   Enable machine's time synchronization with NTP server
   ntp_enable: **true**
   Servers to be used by NTP instead of the default ones (e.g. 0.centos.pool.ntp.org)
   ntp_servers: **["0.centos.pool.ntp.org"]**

   kubernetes_cnis:
     - kubeovn
     - **flannel**

7. then ran ./deploy_ne.sh nodes

**Comment by i-kwilk** [comment]
Hello,
It seems that OVS didn't start. OVS is a part of kube-ovn, in our setup, it is set to use DPDK by default. DPDK reqires hugepages, therefore you need to disable dpdk:

> # group_vars/all/10-default.yml
> kubeovn_dpdk: false

or add some hugepages for example: 

> Enable and configure 1G HugePages:
> # group_vars/controller_group/10-default.yml
>     hugepage_size: "1G"
>     hugepage_amount: "16"
> # group_vars/edgenode_group/10-default.yml
>     hugepage_size: "1G"
>     hugepage_amount: "16"
> # group_vars/all/10-default.yml
> kubeovn_dpdk: true
> kubeovn_dpdk_socket_mem: "1024,1024"
> kubeovn_dpdk_hugepage_size: "1Gi"
> kubeovn_dpdk_hugepages: "12Gi"
> kubeovn_dpdk_resources_requests: "2Gi"
> kubeovn_dpdk_resources_limits: "2Gi"

**Comment by i-kwilk** [comment]
Hi @Jaladi-Devika 

Does the configuration help with the issue?

**Comment by Jaladi-Devika** [comment]
Hi @i-kwilk ,

Got some other issue below is the one. Looks like this is know issue.
https://github.com/open-ness/openness-experience-kits/issues/49


TASK [kubernetes/cni/kubeovn/common : build OVS-DPDK image (this may take some time...)] *************************************************************
task path: /home/sysadmin/Devika/openness-experience-kits/roles/kubernetes/cni/kubeovn/common/tasks/main.yml:89
fatal: [controller]: FAILED! => {
"changed": false
}

MSG:

Thanks,
Devika

**Comment by i-kwilk** [comment]
Hi @Jaladi-Devika 

Right, this is a known issue reported [#49](https://github.com/open-ness/openness-experience-kits/issues/49#issue-689909206) as some RPMs are removed,
we are working on a fix with the team.

Do you agree to close that one?

Regards,
Krzysztof

**Comment by Jaladi-Devika** [comment]
Hi @i-kwilk ,

When can we expect the fix will be ready in 20.06?

Thanks & Regards,
Devika
