### ISSUE TITLE
Missing git2u-all from edge node ansibles

### ISSUE THREAD

**Issue by rsys-asakalab** [open-ness/converged-edge-experience-kits#46]
Possible requirement for many services container builds during openness installation, git2u-all is missing from the edge node os_yum_base_packages.

https://github.com/open-ness/openness-experience-kits/blob/fa5039031d1e639c1695d500d26995aed07d650f/group_vars/edgenode_group/10-default.yml#L77

**Comment by archie951** [comment]
Hi @discoveravis,

You can run below two commands in order to remove previous git versions and keep only git 2.16.x version:

yum remove -y git*
yum install -y --enablerepo=ius-archive git2u-all  

Regards,
Archit

**Comment by i-kwilk** [comment]
Hi @discoveravis 

Thanks for your suggestion, we are aware of the git change,
this will be updated during the next release.

Thanks,
Krzysztof
