### ISSUE TITLE
Error in Downloading OVN tools Task

### ISSUE THREAD

**Issue by vaghesh** [open-ness/converged-edge-experience-kits#47]
Looks like following links are not available to download OVN and OpenvSwitch,
[https://github.com/alauda/ovs/releases/download/2.12.0-5/openvswitch-2.12.0-5.el7.x86_64.rpm ](https://github.com/alauda/ovs/releases/download/2.12.0-5/openvswitch-2.12.0-5.el7.x86_64.rpm)
[https://github.com/alauda/ovs/releases/download/2.12.0-5/ovn-2.12.0-5.el7.x86_64.rpm](https://github.com/alauda/ovs/releases/download/2.12.0-5/ovn-2.12.0-5.el7.x86_64.rpm)

Here is the error log from the OpenNESS Experience Kit, 

TASK [kubernetes/cni/kubeovn/master : download OVN tools] **************************************************************************************************
task path: /root/netowrking_export28.08/esb_modules/OpenNESS/openness-experience-kits/roles/kubernetes/cni/kubeovn/master/tasks/main.yml:26
FAILED - RETRYING: download OVN tools (10 retries left).
FAILED - RETRYING: download OVN tools (9 retries left).
FAILED - RETRYING: download OVN tools (8 retries left).
FAILED - RETRYING: download OVN tools (7 retries left).
FAILED - RETRYING: download OVN tools (6 retries left).
FAILED - RETRYING: download OVN tools (5 retries left).
FAILED - RETRYING: download OVN tools (4 retries left).
FAILED - RETRYING: download OVN tools (3 retries left).
FAILED - RETRYING: download OVN tools (2 retries left).
FAILED - RETRYING: download OVN tools (1 retries left).
fatal: [controller]: FAILED! => {
"attempts": 10,
"changed": true,
"cmd": [
"yum",
"install",
"--downloadonly",
"-y",
"https://github.com/alauda/ovs/releases/download/2.12.0-5/openvswitch-2.12.0-5.el7.x86_64.rpm",
"https://github.com/alauda/ovs/releases/download/2.12.0-5/ovn-2.12.0-5.el7.x86_64.rpm"
],
"delta": "0:00:00.493374",
"end": "2020-08-31 07:08:27.686831",
"rc": 1,
"start": "2020-08-31 07:08:27.193457"
}

STDERR:

Cannot open: https://github.com/alauda/ovs/releases/download/2.12.0-5/openvswitch-2.12.0-5.el7.x86_64.rpm. Skipping.
Cannot open: https://github.com/alauda/ovs/releases/download/2.12.0-5/ovn-2.12.0-5.el7.x86_64.rpm. Skipping.
Error: Nothing to do

**Comment by krishnajs** [comment]
https://github.com/alauda/ovs project recently removed all the previous RPMs (Changes and releases). This is impacting the 20.06 OEK when we select kube-ovn as the CNI. We are working with alauda and have been informed that it was accidentally deleted. 4 out of 6 RPMs have been restored. The below once are still missing. We are working on a fix with the team.

https://github.com/alauda/ovs/releases/download/2.12.0-5/openvswitch-2.12.0-5.el7.x86_64.rpm 
https://github.com/alauda/ovs/releases/download/2.12.0-5/openvswitch-devel-2.12.0-5.el7.x86_64.rpm

**Comment by krishnajs** [comment]
OVN 20.06 fix is now available - https://github.com/open-ness/openness-experience-kits/tree/openness-20.06-ovn-fix
