### ISSUE TITLE
Deployment fails while building ovs-dpdk image

### ISSUE THREAD

**Issue by amitinfo2k** [open-ness/converged-edge-experience-kits#53]
OpenNess version : 20.06

Deployment fails with following error while building the ovs-dpdk image .

`RUNrpm -ivh ~/ovs-${OVS_VERSION}-${OVS_SUBVERSION}/rpm/rpmbuild/RPMS/x86_64/openvswitch-${OVS_VERSION}-${OVS_SUBVERSION}.el7.x86_64.rpm &&     rpm -ivh ~/ovs-${OVS_VERSION}-${OVS_SUBVERSION}/rpm/rpmbuild/RPMS/x86_64/openvswitch-devel-${OVS_VERSION}-${OVS_SUBVERSION}.el7.x86_64.rpm &&     rpm -ivh https://github.com/alauda/ovs/releases/download/${OVS_VERSION}-${OVS_SUBVERSION}/ovn-${OVS_VERSION}-${OVS_SUBVERSION}.el7.x86_64.rpm &&     rpm -ivh https://github.com/alauda/ovs/releases/download/${OVS_VERSION}-${OVS_SUBVERSION}/ovn-vtep-${OVS_VERSION}-${OVS_SUBVERSION}.el7.x86_64.rpm &&     rpm -ivh https://github.com/alauda/ovs/releases/download/${OVS_VERSION}-${OVS_SUBVERSION}/ovn-central-${OVS_VERSION}-${OVS_SUBVERSION}.el7.x86_64.rpm &&     rpm -ivh https://github.com/alauda/ovs/releases/download/${OVS_VERSION}-${OVS_SUBVERSION}/ovn-host-${OVS_VERSION}-${OVS_SUBVERSION}.el7.x86_64.rpm', u'\n', u' ---> Running in b21506f1bad2\n', u'\x1b[91merror: open of /root/ovs-2.12.0-5/rpm/rpmbuild/RPMS/x86_64/openvswitch-2.12.0-5.el7.x86_64.rpm failed: No such file or directory\`

Seems it related to OVN (broken dependancy)
https://github.com/open-ness/edgenode/releases/tag/openness-20.06-ovn-fix

Attaching the complete ansible log

**Comment by amitinfo2k** [comment]
[2020-09-03_10-25-16_ansible.log](https://github.com/open-ness/openness-experience-kits/files/5168241/2020-09-03_10-25-16_ansible.log)

**Comment by archie951** [comment]
Hi @amitinfo2k ,

You are correct, it was because of broken dependency but it has been fixed. Can you please run the cleanup script once and clone the git repository again and try to deploy. 
Let us know if you still face this issue.

Regards,
Archit

**Comment by amitinfo2k** [comment]
Yes, working for me now.
