### ISSUE TITLE
When can we get stable openness 20.03 code base?

### ISSUE THREAD

**Issue by Jaladi-Devika** [open-ness/converged-edge-experience-kits#60]
Hi Team,

Can anyone please let us know when can we get stable openness 20.03 code base?
As I posted in forum we are unable to deploy openness 20.03. Please look into issue link fro more details.
https://github.com/open-ness/openness-experience-kits/issues/51

Thanks & Regards,
Devika

**Comment by tomaszwesolowski** [comment]
Hi,
From what I can see in this error message I believe this is related to issue we faced with one of our dependencies. This issue has been fixed for version 20.06 and we highly suggest trying that version.
