### ISSUE TITLE
onpremise edge node deployment fails with unresolved url 

### ISSUE THREAD

**Issue by idirect-dev** [open-ness/converged-edge-experience-kits#7]
deploy_onprem_node.sh fails with:
"Failure downloading http://lxsoft106.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-5.el7_7.1.noarch.rpm, Request failed: <urlopen error [Errno -2] Name or service not known>"
This url does not resolve, and consequently the deployment faills.
Ansible log attached.
[2020-01-28_10-31-17_ansible_onprem_deploy_node_loc-dev_fail.log](https://github.com/open-ness/openness-experience-kits/files/4122039/2020-01-28_10-31-17_ansible_onprem_deploy_node_loc-dev_fail.log)

**Comment by idirect-dev** [comment]
I have succeeded in deploying the node with the following workaround.
I hosted the missing rpm (tuned-profiles-realtime-2.11.0-5.el7_7.1.noarch.rpm) locally
I modified the hosts file on the edge node to point to my local http server instead of  http://lxsoft106.cern.ch

**Comment by patrykxmatuszak** [comment]
Hi, thanks for your feedback.

We also noticed that lxsoft106.cern.ch is no longer reachable, so we're now using different URL: http://linuxsoft.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-5.el7_7.1.noarch.rpm

To avoid editing hosts, you can edit second item of `os_kernel_rt_tuned_package_urls` variable in `roles/os_kernelrt/defaults/main.yml` file:
```
os_kernel_rt_tuned_package_urls:
- "http://mirror.centos.org/centos/7/updates/x86_64/Packages/tuned-2.11.0-5.el7_7.1.noarch.rpm"
- "http://linuxsoft.cern.ch/scientific/7x/x86_64/updates/fastbugs/tuned-profiles-realtime-2.11.0-5.el7_7.1.noarch.rpm"
```

**Comment by amr-mokhtar** [comment]
Hi @idirect-dev, Was your problem resolved?

**Comment by idirect-dev** [comment]
Changing to linuxsoft.cern.ch resolves this issue.
