### ISSUE TITLE
Error while deployment v20.12 : No matching distribution found for slip==0.4.0

### ISSUE THREAD

**Issue by AmanThakral02** [open-ness/converged-edge-experience-kits#76]
Trying on 20.12

While deploying getting error:

ERROR: Could not find a version that satisfies the requirement slip==0.4.0 

[2020-12-21_06-46-33_ansible.log](https://github.com/open-ness/openness-experience-kits/files/5722804/2020-12-21_06-46-33_ansible.log)

**Comment by amr-mokhtar** [comment]
Hi @AmanThakral02!! Did you install on a fresh OS? Remember that 20.12 release is based on CentOS 7.8 Minimal. CentOS 7.8 must be installed on all nodes (controller & workers)

**Comment by AmanThakral02** [comment]
@amr-mokhtar , I am using CentOS 7.8.2003 on both controller and worker

**Comment by tomaszwesolowski** [comment]
Hi @AmanThakral02, 
We're investigating the issue, will get back to you as soon as possible.

**Comment by tomaszwesolowski** [comment]
@AmanThakral02  It looks that you can remove this dependency from roles/docker/files/requirements.txt
remove following lines:
slip==0.4.0
slip.dbus==0.4.0

Those dependencies will be removed in future releases.
