### ISSUE TITLE
Missing Python dependency `pyrsistent==0.16.1` causing OpenNESS deployment failure

### ISSUE THREAD

**Issue by amr-mokhtar** [open-ness/converged-edge-experience-kits#79]
A missing Python dependency was identified in the [OpenNESS 20.12 release](https://github.com/open-ness/openness-experience-kits/releases/tag/openness-20.12) that is impacting OpenNESS deployment.

A quick fix is to apply the following change to file `roles/docker/files/requirements.txt`,

```diff
pygpgme==0.3
pyliblzma==0.5.3
PyNaCl==1.4.0
+pyrsistent==0.16.1
python-linux-procfs==0.4.9
pyudev==0.15
pyxattr==0.5.1
```

**Comment by ishanVshah** [comment]
@amr-mokhtar  I am installing Openness 20.12.1 on fresh servers and I am facing below issue while installing.

:stderr: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Cannot uninstall 'requests'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
WARNING: You are using pip version 20.2.4; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/bin/python2 -m pip install --upgrade pip' command.
