### ISSUE TITLE
Kuberetes Dashboard version issue

### ISSUE THREAD

**Issue by Jorge-Sasiain** [open-ness/converged-edge-experience-kits#82]
Hello,

When I was deploying the OpenNESS controller with Kubernetes-Dashboard enabled I got the following error due to failed metrics-server helm chart dependency:

```
2021-01-13 10:16:56,278 p=19856 u=root n=ansible | TASK [kubernetes/dashboard : download helm chart dependencies] ****************************************************************************************************************************************************************************************************************
2021-01-13 10:16:56,924 p=19856 u=root n=ansible | fatal: [controller]: FAILED! => {
    "changed": true,
    "cmd": [
        "helm",
        "dependency",
        "update"
    ],
    "delta": "0:00:00.411983",
    "end": "2021-01-13 10:16:56.897442",
    "rc": 1,
    "start": "2021-01-13 10:16:56.485459"
}

STDOUT:

Saving 1 charts
Downloading metrics-server from repo https://kubernetes-charts.storage.googleapis.com/
Save error occurred:  could not find : chart metrics-server not found in https://kubernetes-charts.storage.googleapis.com/
Deleting newly downloaded charts, restoring pre-update state


STDERR:

Error: could not find : chart metrics-server not found in https://kubernetes-charts.storage.googleapis.com/


MSG:

non-zero return code
```

Upgrading ``_dashboard_version: v2.0.3`` to ``_dashboard_version: v2.1.0`` in ``roles/kubernetes/dashboard/defaults/main.yml`` fixed it for me (I think v2.0.5 onwards should work), but I'm not sure if this has other implications. Here's the related issue in the Kubernetes-dashboard repository: https://github.com/kubernetes/dashboard/issues/5689, and related commit: https://github.com/kubernetes/dashboard/pull/5666/files

**Comment by tomaszwesolowski** [comment]
Hi @Jorge-Sasiain,
Thanks for your feedback. Upgrading this component shouldn't impact anything in negative way. We will take a closer look at this problem and address it in future releases.
