### ISSUE TITLE
Kubelete dumps errors - can't process manifest file

### ISSUE THREAD

**Issue by Prabhjot-Sethi** [open-ness/converged-edge-experience-kits#89]
Upon successful installation of openness-20.12.02, following errors are constantly dumped as per kubelet logs

[root@oness-01 ~]# service kubelet status
Redirecting to /bin/systemctl status kubelet.service
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Thu 2021-02-25 08:09:50 UTC; 41min ago
     Docs: https://kubernetes.io/docs/
 Main PID: 3415 (kubelet)
    Tasks: 31
   Memory: 99.0M
   CGroup: /system.slice/kubelet.service
           └─3415 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --network-plugin=cni --pod-infr...

**Feb 25 08:51:10 oness-01 kubelet[3415]: E0225 08:51:10.763166    3415 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/extend_scheduler.yml": /etc/kubernetes/manifests/extend_scheduler.yml:...
Feb 25 08:51:10 oness-01 kubelet[3415]: E0225 08:51:10.769336    3415 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/kustomization.yaml": /etc/kubernetes/manifests/kustomization.yaml: cou...**
Feb 25 08:51:13 oness-01 kubelet[3415]: W0225 08:51:13.711171    3415 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container (pod: eaa-69c7bb7b5d-6fv6d, container id: b4...153abc97d2346a)
Feb 25 08:51:13 oness-01 kubelet[3415]: W0225 08:51:13.790898    3415 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container (pod: interfaceservice-6w2kj, container id: ...c37c513cd27631)
Feb 25 08:51:14 oness-01 kubelet[3415]: W0225 08:51:14.970869    3415 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container (pod: edgedns-fv5wx, container id: 30d986542...0624da91f6bc7f)
Feb 25 08:51:25 oness-01 kubelet[3415]: W0225 08:51:25.789777    3415 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container (pod: edgedns-fv5wx, container id: 30d986542...0624da91f6bc7f)
Feb 25 08:51:28 oness-01 kubelet[3415]: W0225 08:51:28.706888    3415 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container (pod: eaa-69c7bb7b5d-6fv6d, container id: b4...153abc97d2346a)
Feb 25 08:51:28 oness-01 kubelet[3415]: W0225 08:51:28.779014    3415 cpu_manager.go:397] [cpumanager] reconcileState: ignoring terminated container (pod: interfaceservice-6w2kj, container id: ...c37c513cd27631)
**Feb 25 08:51:30 oness-01 kubelet[3415]: E0225 08:51:30.763583    3415 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/extend_scheduler.yml": /etc/kubernetes/manifests/extend_scheduler.yml:...
Feb 25 08:51:30 oness-01 kubelet[3415]: E0225 08:51:30.770042    3415 file.go:187] Can't process manifest file "/etc/kubernetes/manifests/kustomization.yaml": /etc/kubernetes/manifests/kustomization.yaml: cou...**
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by archie951** [comment]
Hi Prabhjot,

Can you delete these 2 files (extend_scheduler.yml and kustomization.yaml) in /etc/kubernetes/manifests/ directory. Restarting kubelet should not give above errors/warnings anymore. Please let me know how it goes. Thanks!

Regards,
Archit

**Comment by amr-mokhtar** [comment]
This issue has been identified and fixed internally. Will be included in the upcoming release.
