### ISSUE TITLE
Worker node issue : - wait for running ovs-ovn POD

### ISSUE THREAD

**Issue by ravicorning** [open-ness/converged-edge-experience-kits#93]
I was asked to post on the forum, but don't see any responses, some guidance to the open issues will help.

Without enabling kubeovn/SRIOV, the worker node deployment went fine. But, when i enable this, it is waiting for the OVS-OVN POD to come up on the worker node, please see the logs. I saw someone reported a similar issue with an older openness release, where it was addressed by setting the right huge page size in, guess that was a older release, that path wasn't holding good, mapped it to  roles/kubernetes/cni/kubeovn/controlplane/defaults/main.yml , the outcome is the same.

I'm not using any flavor during deployment, changes are in group_vars/all/10-default.yml, node-group, where ever hugepage setting is involed to 1Gi, and 20Gi in total.

I see the many ovn pod related pods in a bad state, from the controller:

kube-system   kube-ovn-cni-8hl82                                           0/1     CrashLoopBackOff    47         151m
kube-system   kube-ovn-cni-kp6tk                                           1/1     Running             2          179m
kube-system   kube-ovn-controller-76d6bd7c8d-szkk7                         1/1     Running             1          179m
kube-system   kube-ovn-pinger-cx755                                        1/1     Running             0          178m
kube-system   kube-ovn-pinger-mjvdj                                        0/1     ContainerCreating   0          151m
kube-system   kube-proxy-l6fcd                                             1/1     Running             0          3h
kube-system   kube-proxy-q7jx9                                             1/1     Running             1          151m
kube-system   kube-scheduler-corningopenness                               1/1     Running             2          168m
kube-system   ovn-central-7d996765d6-fdhnc                                 1/1     Running             0          112m
kube-system   ovs-ovn-cm25k                                                1/1     Running             1          179m
kube-system   ovs-ovn-rbxcb                                                0/1     Pending             0          151m

###

Permanent and Non-Permanent(immediate) operation
redirecting (type: modules) ansible.builtin.firewalld to community.general.firewalld
redirecting (type: modules) community.general.firewalld to ansible.posix.firewalld
ok: [node01] => (item=8472/udp) => {
    "ansible_loop_var": "item", 
    "changed": false, 
    "item": "8472/udp"
}

MSG:

Permanent and Non-Permanent(immediate) operation

TASK [kubernetes/cni/kubeovn/node : wait for running ovs-ovn pod] **************************************************************************************************************
fatal: [node01 -> 10.12.87.83]: FAILED! => {
    "attempts": 30, 
    "changed": false, 
    "cmd": "set -o pipefail && kubectl get pods -n kube-system -o custom-columns=NAME:.metadata.name,STATUS:.status.phase --no-headers --field-selector spec.nodeName=opennesswkn-1 | grep -E \"ovs-ovn\"\n", 
    "delta": "0:00:00.115373", 
    "end": "2021-03-05 16:03:36.044027", 
    "rc": 1, 
    "start": "2021-03-05 16:03:35.928654"
}

MSG:

non-zero return code

**Comment by archie951** [comment]
Hi @ravicorning , Can you please let us know the hardware specs, size and RAM tried for this installation. If you are using bare-metal please describe the specs of that hardware too. Also please share the logs and group_vars/all/10-default.yml from oek.
We have introduced a new tag 20.12.02. Request you to give that one a try too.

Regards,
Archit

**Comment by ravicorning** [comment]
Hi Archit, this issue was resolved..opened a new issue on getting the OPAE compiled in the worker node, hope you can help..
