### ISSUE TITLE
Docker push to opneness controller's docker registry

### ISSUE THREAD

**Issue by ravicorning** [open-ness/converged-edge-experience-kits#97]
I see most of the docker images in the edge apps are build locally in the controller. Is there a way to push images from other hosts into openness ?, any related documentation related to docker login/docker push how to enable this on openness ?

**Comment by archie951** [comment]
Hi @ravicorning, 
https://github.com/open-ness/specs/blob/af8839b8405d085564ab8e428dcf6243334e3bb2/doc/getting-started/network-edge/controller-edge-node-setup.md#harbor-registry

Regards,
Archit
